name: Build Geode Mod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Geode mod for Android
        uses: geode-sdk/build-geode-mod@main
        id: build-android
        with:
          sdk: "latest"
          target: "Android64"

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-outside-bro-android64
          path: ${{ steps.build-android.outputs.build-output }}

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Geode mod for Windows
        uses: geode-sdk/build-geode-mod@main
        id: build-win
        with:
          sdk: "latest"
          target: "Win64"

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-outside-bro-win64
          path: ${{ steps.build-win.outputs.build-output }}

  release:
    name: Create Latest Release
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: go-outside-bro-android64
          path: release-files/android

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: go-outside-bro-win64
          path: release-files/windows

      - name: Delete old latest release
        continue-on-error: true
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create latest tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag latest
          git push -f origin latest

      - name: Create latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: |
            release-files/android/**
            release-files/windows/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
